services:
  ghost:
    image: ghost:5.119.3
    restart: always
    ports:
      - 8080:2368
      - 35729:35729
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://localhost:8080
      NODE_ENV: development
    networks:
      - ghost
    volumes:
      - /opt/ghost/content:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
    networks:
      - ghost_db
      - ghost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - 9000:80
    networks:
      - ghost_db
    environment:
        PMA_ARBITRARY: 1
        MYSQL_ROOT_PASSWORD: example
        MYSQL_USER: root
        MYSQL_PASSWORD: example

volumes:
  ghost:
  db:

networks:
  ghost:
  ghost_db:
